# Generated by Django 2.2 on 2019-04-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Batch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Batch'),
        ),
    ]
